### ISSUE TITLE
Prepare for v1 release :tada:

### ISSUE THREAD

**Issue by ollieread** [sprout-laravel/sprout#44]
The following need to happen before we can look at a v1 tag:

- [x] #91 
- [x] #36
- [x] #92
- [x] #95 
- [ ] Complete documentation

Once those parts of the code/documentation have been completed, the following needs to happen with the repo:

- [x] Update the org repo
- [x] Update the readme
- [ ] Create contribution guidelines
- [x] Create other community guidelines and files
- [ ] Document the particular flavour of conventional commits
- [ ] Create issue, pull-request and any other templates

And finally, these two tasks:

- [x] Create `.gitattributes`
- [ ] Generate changelog
- [ ] Tag v1.0.0
